### PR TITLE
Kill Fix

### PR DESCRIPTION
**Pull request by xyjx001**
Fixed an issue where sheriff couldn't kill Impostor or Jackal when SheriffCanKillAll option is on

### CODE REVIEW

**Comment by tanakanira0118** [comment]
Am I correct in assuming that the issue is that the impostor or jackal cannot kill when set up this way?
image

**Comment by xyjx001** [comment]
Yep, that's right

**Comment by tanakanira0118** [comment]
> Yep, that's right

The original code does can the kill properly and the code seems fine, but what was the idea behind changing the code to this?
image

**Comment by xyjx001** [comment]
Weird, since about 1-2 week ago, people in my game room told me  they couldn't kill imposters or jackal as a sheriff.
Imposters and jackal couldn't kill eeach other as well. 
So i used my pc and mobile to test this, I only made them 3 avaliable.   i found sheriff, imposters jackal couldn't kill others.
Then i checked the  code and found it could be the SheriffCanKillAll option. Then changed it to seperately and made all the sub options on, and then the kill worked. Thus, i made the above code change.
I found another issue,  when my mobile got assigned the jackal role, there is a 20-30% chance it would be assigned a scientist role instead. andd couldn't perform kill

**Comment by tanakanira0118** [comment]
> Weird, since about 1-2 week ago, people in my game room told me they couldn't kill imposters or jackal as a sheriff.
> Imposters and jackal couldn't kill eeach other as well.
> So i used my pc and mobile to test this, I only made them 3 avaliable. i found sheriff, imposters jackal couldn't kill others.

Is this 100% reproducible?

At least in my environment we can kill each other without problems.

> Then i checked the code and found it could be the SheriffCanKillAll option. Then changed it to seperately and made all the sub options on, and then the kill worked. Thus, i made the above code change.

If "SheriffCanKillAll" is the cause as you say, how do you explain the problem of Impostor and Jackal can't killing each other off?

> I found another issue, when my mobile got assigned the jackal role, there is a 20-30% chance it would be assigned a scientist role instead. andd couldn't perform kill

This is clearly not due to the code in this section.

**Comment by xyjx001** [comment]
it was almost 100% reproducable. I'm performing a dry run and will get back to you after i get the test result.

**Comment by tanakanira0118** [comment]
> it was almost 100% reproducable. I'm performing a dry run and will get back to you after i get the test result.

If you can reproduce it, please create a bug report ticket on Discord and attach the log.

**Comment by xyjx001** [comment]
The fix didn't work during the 2 public test. a sheriff and a jackal couldn't kill each other. #ticket-0454 logged

**Pull request closed without merging**
