### PR TITLE
Remove unnecessary code: Remove pet at dead players (Vanilla bug fixed long ago)

### PR DESCRIPTION
**Pull request by Tommy-XL**

### CODE REVIEW

**Comment by Hyz-sui** [comment]
It seems that has not be fixed?
I'm not sure, but to our horror, it may be a spec😨

image

**Comment by Tommy-XL** [comment]
Previously, the pet followed the ghost, but now it just stays where the player was killed, so

**Comment by Tommy-XL** [comment]
This is how pets have always worked, but in one of the versions that was released in the summer of 2023 there was a bug in which the pets followed the ghost and all players saw it

**Comment by Tommy-XL** [comment]
I was wrong, it was sometime in October
image
image

**Comment by Hyz-sui** [comment]
Ah, I understand. This is considered a bug among Japanese players since pets staying in the dead body's (or exiled player's last) position makes the game not possible to be played fairly.
This issue is occurring since around the HideNSeek update.
So this code cannot be removed completely.

**Comment by Tommy-XL** [comment]
Hmm, ok, i understand

**Comment by Hyz-sui** [comment]
Thank you for your PR!

**Pull request closed without merging**
