### PR TITLE
Replenish the missing quotations

### PR DESCRIPTION
**Pull request by ZeMingoh233**
Replenished the missing quotations in English and TChinese text.
Restatement: We're translators of Simplyfied Chinese. We're not responsible for TChinese translation.
However, we consider the missing of quotations as our misconduct during the translation. Sincerely apology.

### CODE REVIEW

**Comment by MC-AS-Huier** [comment]
This is the open source community, not a place for you to monopolize

**Comment by NetherDragonTw** [comment]
嘿, 我好像沒聽說什麼我有遺漏內容呢, 如果有問題請指出地方, 每次重新翻譯時我都有檢查過, 請問遺漏內容在哪呢?

**Comment by MC-AS-Huier** [comment]
你沒有翻譯遺漏的地方，我只是想跟你合作，如果你沒有這個意願的話請無視












梦初（MC_AS_Huier）
***@***.***


---Original---
From: ***@***.***&gt;
Date: Thu, Aug 11, 2022 16:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tukasa0001/TownOfHost] Replenish the missing quotations (PR #1002)




 
嘿, 我好像沒聽說什麼我有遺漏內容呢, 如果有問題請指出地方, 每次重新翻譯時我都有檢查過, 請問遺漏內容在哪呢?

**Comment by NetherDragonTw** [comment]
> 
你的意思說他是想跟我合作?
還是要跟你合作?

**Comment by ZeMingoh233** [comment]
> 嘿, 我好像沒聽說什麼我有遺漏內容呢, 如果有問題請指出地方, 每次重新翻譯時我都有檢查過, 請問遺漏內容在哪呢? (我是繁體中文翻譯者)

您好。您的翻译没有什么问题。
因为我这边翻译途中出了一点问题，翻译文本中的引号丢失，我手动将其补回。
我并没修改您的翻译文本。感谢您为模组翻译做出的贡献。
至于和简中译者的矛盾，我会与其单独沟通。
非常感谢。

**Comment by NetherDragonTw** [comment]
> > 嘿, 我好像沒聽說什麼我有遺漏內容呢, 如果有問題請指出地方, 每次重新翻譯時我都有檢查過, 請問遺漏內容在哪呢? (我是繁體中文翻譯者)
> 
> 您好。您的翻译没有什么问题。 因为我这边翻译途中出了一点问题，翻译文本中的引号丢失，我手动将其补回。 我并没修改您的翻译文本。感谢您为模组翻译做出的贡献。 至于和简中译者的矛盾，我会与其单独沟通。 非常感谢。

好喔, 抱歉誤會您

**Comment by ZeMingoh233** [comment]
> This is the open source community, not a place for you to monopolize

May I ask whether you get our permission to use our translation text or not?

**Comment by MC-AS-Huier** [comment]
This is the open source community....And is this called use?Your signature on it indicates your contribution。However, the simplified Chinese column is not only yours。












梦初（MC_AS_Huier）
***@***.***


---Original---
From: ***@***.***&gt;
Date: Thu, Aug 11, 2022 16:27 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tukasa0001/TownOfHost] Replenish the missing quotations (PR#1002)




  
This is the open source community, not a place for you to monopolize
  
May I ask whether you get our permission to use our translation text or not?

**Comment by MC-AS-Huier** [comment]
和我
我和我的朋友成立兩個少年漢化組，我希望你能幫助我們對其他模組進行繁體中文翻譯












梦初（MC_AS_Huier）
***@***.***


---Original---
From: ***@***.***&gt;
Date: Thu, Aug 11, 2022 16:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tukasa0001/TownOfHost] Replenish the missing quotations (PR#1002)




   
你的意思說他是想跟我合作?
 還是要跟你合作?

**Comment by ZeMingoh233** [comment]
> This is the open source community....And is this called use?Your signature on it indicates your contribution。However, the simplified Chinese column is not only yours。 梦初（MC_AS_Huier） ***@***.***
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Thu, Aug 11, 2022 16:27 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [tukasa0001/TownOfHost] Replenish the missing quotations (PR#1002) This is the open source community, not a place for you to monopolize May I ask whether you get our permission to use our translation text or not? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

I'm not talking about contribution. I'm accusing for the immorality of your group.
We're not going to monopolize the rights of translation. On the contrary, we're glad for the prosperity of Simlified Chinese Among Us society.
In fact, your translation is the one who break the principle.
You directly moved half of our translation text into yours without notifying us who are still providing translation for developers.
What's more, you belittled our translation as "not perfect", and on this ground you changed the translation on github by the pull request.
Do you think we will trust a group who has done such things?Don't we deserve your apology?
I've deleted your signature from the file for you make no contribution to our translation.
I hope you can understand. Thank you.

**Comment by MC-AS-Huier** [comment]
We also don't believe that a Chinese group that will monopolize and suppress small-scale Chinese groups will leave you alone. We also don't recognize your attitude and try to make peace talks but threaten them








梦初（MC_AS_Huier）
***@***.***


---Original---
From: ***@***.***&gt;
Date: Thu, Aug 11, 2022 17:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tukasa0001/TownOfHost] Replenish the missing quotations (PR #1002)




  
This is the open source community....And is this called use?Your signature on it indicates your contribution。However, the simplified Chinese column is not only yours。 梦初（MC_AS_Huier） @.***
 …
 ---Original--- From: @.&gt; Date: Thu, Aug 11, 2022 16:27 PM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [tukasa0001/TownOfHost] Replenish the missing quotations (PR#1002) This is the open source community, not a place for you to monopolize May I ask whether you get our permission to use our translation text or not? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
I'm not talking about contribution. I'm accusing for the immorality of your group.
 We're not going to monopolize the rights of translation. On the contrary, we're glad for the prosperity of Simlified Chinese Among Us society.
 In fact, your translation is the one who break the principle.
 You directly moved half of our translation text into yours without notifying us who are still providing translation for developers.
 What's more, you belittled our translation as "not perfect", and on this ground you changed the translation on github by the pull request.
 Do you think we will trust a group who has done such things?Don't we deserve your apology?
 I've deleted your signature from the file for you make no contribution to our translation.
 I hope you can understand. Thank you.

**Comment by ZeMingoh233** [comment]
> 

Please take a good look at what I said. I have no need to answer your question. You do.
I **have** make peace talk with you. It's you who dodge my statement.

**Comment by MC-AS-Huier** [comment]
I said that when I was another team member, you had a good conversation, but your solution was full of repression and monopoly












梦初（MC_AS_Huier）
***@***.***


---Original---
From: ***@***.***&gt;
Date: Thu, Aug 11, 2022 18:09 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tukasa0001/TownOfHost] Replenish the missing quotations (PR#1002)




   
Please take a good look at what I said. I have no need to answer your question. You do.
 I have made peace talk with you. It's you who dodge my statement.

**Comment by NetherDragonTw** [comment]
> 和我 我和我的朋友成立兩個少年漢化組，我希望你能幫助我們對其他模組進行繁體中文翻譯 梦初（MC_AS_Huier） ***@***.***
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Thu, Aug 11, 2022 16:23 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [tukasa0001/TownOfHost] Replenish the missing quotations (PR#1002) 你的意思說他是想跟我合作? 還是要跟你合作? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

我可否拒絕? 因為我還有學業在身, 沒有太多時間做漢化 如果需要我的幫助的話請留下聯繫方式(discord)

**Comment by ZeMingoh233** [comment]
> I said that when I was another team member, you had a good conversation, but your solution was full of repression and monopoly 梦初（MC_AS_Huier） ***@***.***
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Thu, Aug 11, 2022 18:09 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [tukasa0001/TownOfHost] Replenish the missing quotations (PR#1002) Please take a good look at what I said. I have no need to answer your question. You do. I have made peace talk with you. It's you who dodge my statement. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

Please don't evade the crucial point. 
We didn't mean anything like repression and monopoly. 
Don't forget, you and I are doing the same thing here.
If this is even monopoly, shouldn't you be usurpers and dictators?
We're just asking whether you've got our permission.
You use most part of our translation; you did not inform us.
It's enough for us to distrust you.
Please don't challenge our baseline. Answer our question.
**Did you get our permission to use our translation text?**
-

**Comment by MC-AS-Huier** [comment]
可以，我們的discord服務器在我的倉庫的我們漢化組的介紹文件裏有












梦初（MC_AS_Huier）
***@***.***


---Original---
From: ***@***.***&gt;
Date: Thu, Aug 11, 2022 18:18 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tukasa0001/TownOfHost] Replenish the missing quotations (PR#1002)




  
和我 我和我的朋友成立兩個少年漢化組，我希望你能幫助我們對其他模組進行繁體中文翻譯 梦初（MC_AS_Huier） @.***
 …
 ---Original--- From: @.&gt; Date: Thu, Aug 11, 2022 16:23 PM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [tukasa0001/TownOfHost] Replenish the missing quotations (PR#1002) 你的意思說他是想跟我合作? 還是要跟你合作? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
我可否先暫時拒絕? 因為我還有學業在身, 沒有太多時間做漢化 如果需要我的幫助的話請留下聯繫方式(discord)

**Comment by xiaojinna** [comment]
> > This is the open source community....And is this called use?Your signature on it indicates your contribution。However, the simplified Chinese column is not only yours。 梦初（MC_AS_Huier） _**@**_.***
> > […](#)
> > ---Original--- From: _**@**_._**> Date: Thu, Aug 11, 2022 16:27 PM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [tukasa0001/TownOfHost] Replenish the missing quotations (PR#1002) This is the open source community, not a place for you to monopolize May I ask whether you get our permission to use our translation text or not? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: _**@**_.***>
> 
> I'm not talking about contribution. I'm accusing for the immorality of your group. We're not going to monopolize the rights of translation. On the contrary, we're glad for the prosperity of Simlified Chinese Among Us society. In fact, your translation is the one who break the principle. You directly moved half of our translation text into yours without notifying us who are still providing translation for developers. What's more, you belittled our translation as "not perfect", and on this ground you changed the translation on github by the pull request. Do you think we will trust a group who has done such things?Don't we deserve your apology? I've deleted your signature from SChinese translator in the file for you make no contribution to our translation. As for the TChinese, I respect your work and I make no change to the text at all, only making up the quotations. I hope you can understand. Thank you.

Each of us can participate in the translation of simplified Chinese. We will not be like your team. We just want it to support Simplified Chinese, and we cannot develop peacefully together? Are you correct the translation content of your team? Moreover, everyone's name for occupation is different. Can you guarantee that your team's Chineseization is absolutely perfect? Blind monopoly and advertising your team, we need a clean module! You should be shameful for your team's behavior!

**Comment by fivefirex** [comment]
@MC-AS-Huier @xiaojinna 
What are you talking about? You're the one who's at **FAULT**! Isn't it enough that you used **A LARGE PART of OUR TRANSLATED TEXT** without our permission? And you say on Github that our translation is **NOT PERFECT**? Would your "perfect text" be there WITHOUT our text?
**YOU DON'T RESPECT THE RESULTS OF OUR WORK!**
Open source community ... **Is it okay to STEAL someone's work in an open source community?** Don't think you're all right and everyone else is WRONG!

```
(GPL v3)

...

  To "propagate" a work means to do anything with it that, without
permission, would make you directly or secondarily liable for
infringement under applicable copyright law, except executing it on a
computer or modifying a private copy.  Propagation includes copying,
distribution (with or without modification), making available to the
public, and in some countries other activities as well.

...

Therefore, by modifying or propagating a
covered work, you indicate your acceptance of this License to do so.

...

```

**You and I are both Chinese, and I am really ASHAMED and ANGRY!**
Hope you understand. Thanks, *maybe*.

**Comment by ZeMingoh233** [comment]
> 

Don't change the subject with monopoly.

**Comment by MC-AS-Huier** [comment]
既然你们这么说，好好好，我的错，我道歉：我对我正常流程更新翻译道歉，我对我私自添加我的贡献道歉。你们随意吧，反正我摆烂了，我不管csv文件的翻译了。












梦初（MC_AS_Huier）
***@***.***


---Original---
From: ***@***.***&gt;
Date: Thu, Aug 11, 2022 18:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tukasa0001/TownOfHost] Replenish the missing quotations (PR #1002)




   
Don't change the subject with monopoly.

**Comment by fivefirex** [comment]
> 既然你们这么说，好好好，我的错，我道歉：我对我正常流程更新翻译道歉，我对我私自添加我的贡献道歉。你们随意吧，反正我摆烂了，我不管csv文件的翻译了。 梦初（MC_AS_Huier） ***@***.***
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Thu, Aug 11, 2022 18:32 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [tukasa0001/TownOfHost] Replenish the missing quotations (PR #1002) Don't change the subject with monopoly. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

你挑衅谁呢？年龄不大倒挺嚣张啊，不会说话的话建议把九年义务教育语文学完，你估计一年都没学完吧
你和那个硬币捆一块没一个拿得出手的作品，toh还要跟我们抢，以后不知道你要走向什么道路，老子不敢想，想了也是浪费时间
既然你会看github写csharps就应该走些正当的道路，受正规教育将来有大用，比你在这盗走别人的劳动成果不知道强几万倍

**Comment by MC-AS-Huier** [comment]
好，我道歉我未经允许修改了你们的内容，我是坏人，我就活该活在这个世上，来呀来把我杀了，杀了我这个罪大恶极的人，杀了我这个像反抗的人，让我来个解脱，我没别的目标，我唯一的目标就是活的死了后解脱，如果你说我是疯子，说我没受过教育，说我是精神病，你随意，我不管了










梦初（MC_AS_Huier）
***@***.***


---Original---
From: ***@***.***&gt;
Date: Thu, Aug 11, 2022 18:53 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tukasa0001/TownOfHost] Replenish the missing quotations (PR#1002)




  
既然你们这么说，好好好，我的错，我道歉：我对我正常流程更新翻译道歉，我对我私自添加我的贡献道歉。你们随意吧，反正我摆烂了，我不管csv文件的翻译了。 梦初（MC_AS_Huier） @.***
 …
 ---Original--- From: @.&gt; Date: Thu, Aug 11, 2022 18:32 PM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [tukasa0001/TownOfHost] Replenish the missing quotations (PR #1002) Don't change the subject with monopoly. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
你挑衅谁呢？年龄不大倒挺嚣张啊，不会说话的话建议把九年义务教育语文学完，你估计一年都没学完吧
 你和那个硬币捆一块没一个拿得出手的作品，toh还要跟我们抢，以后不知道你要走向什么道路，老子不敢想，想了也是浪费时间
 既然你会看github写csharps就应该走些正当的道路，受正规教育将来有大用，比你在这盗走别人的劳动成果不知道强几万倍

**Comment by MC-AS-Huier** [comment]
你随意，你要说你随意，我已经被说过很多次类似的话了，我就是罪大恶极的人，只能苟活在这个世上












梦初（MC_AS_Huier）
***@***.***


---Original---
From: ***@***.***&gt;
Date: Thu, Aug 11, 2022 18:53 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tukasa0001/TownOfHost] Replenish the missing quotations (PR#1002)




  
既然你们这么说，好好好，我的错，我道歉：我对我正常流程更新翻译道歉，我对我私自添加我的贡献道歉。你们随意吧，反正我摆烂了，我不管csv文件的翻译了。 梦初（MC_AS_Huier） @.***
 …
 ---Original--- From: @.&gt; Date: Thu, Aug 11, 2022 18:32 PM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [tukasa0001/TownOfHost] Replenish the missing quotations (PR #1002) Don't change the subject with monopoly. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
你挑衅谁呢？年龄不大倒挺嚣张啊，不会说话的话建议把九年义务教育语文学完，你估计一年都没学完吧
 你和那个硬币捆一块没一个拿得出手的作品，toh还要跟我们抢，以后不知道你要走向什么道路，老子不敢想，想了也是浪费时间
 既然你会看github写csharps就应该走些正当的道路，受正规教育将来有大用，比你在这盗走别人的劳动成果不知道强几万倍

**Comment by NetherDragonTw** [comment]
> > 既然你们这么说，好好好，我的错，我道歉：我对我正常流程更新翻译道歉，我对我私自添加我的贡献道歉。你们随意吧，反正我摆烂了，我不管csv文件的翻译了。 梦初（MC_AS_Huier） _**@**_.***
> > […](#)
> > ---Original--- From: _**@**_._**> Date: Thu, Aug 11, 2022 18:32 PM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [tukasa0001/TownOfHost] Replenish the missing quotations (PR #1002) Don't change the subject with monopoly. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: _**@**_.***>
> 
> 你挑衅谁呢？年龄不大倒挺嚣张啊，不会说话的话建议把九年义务教育语文学完，你估计一年都没学完吧 你和那个硬币捆一块没一个拿得出手的作品，toh还要跟我们抢，以后不知道你要走向什么道路，老子不敢想，想了也是浪费时间 既然你会看github写csharps就应该走些正当的道路，受正规教育将来有大用，比你在这盗走别人的劳动成果不知道强几万倍

沒錯, 這傢伙還搬走我的繁體中文翻譯, 我已經沒跟他計較甚麼了, 我自己不想惹事上身

**Comment by JieGeLovesDengDuaLang** [comment]
> > 既然你们这么说，好好好，我的错，我道歉：我对我正常流程更新翻译道歉，我对我私自添加我的贡献道歉。你们随意吧，反正我摆烂了，我不管csv文件的翻译了。 梦初（MC_AS_Huier） _**@**_.***
> > […](#)
> > ---Original--- From: _**@**_._**> Date: Thu, Aug 11, 2022 18:32 PM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [tukasa0001/TownOfHost] Replenish the missing quotations (PR #1002) Don't change the subject with monopoly. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: _**@**_.***>
> 
> 你挑衅谁呢？年龄不大倒挺嚣张啊，不会说话的话建议把九年义务教育语文学完，你估计一年都没学完吧 你和那个硬币捆一块没一个拿得出手的作品，toh还要跟我们抢，以后不知道你要走向什么道路，老子不敢想，想了也是浪费时间 既然你会看github写csharps就应该走些正当的道路，受正规教育将来有大用，比你在这盗走别人的劳动成果不知道强几万倍

乐了，我们硬币什么时候和两个少年他们合作了？我们硬币汉化我们自己的，根本就没参与你们这讨论里面，关我们硬币什么事？惹你们了？存心找我们茬？

**Comment by MC-AS-Huier** [comment]
确实没合作，我也没说我们合作。








梦初（MC_AS_Huier）
***@***.***


---Original---
From: ***@***.***&gt;
Date: Fri, Aug 12, 2022 12:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tukasa0001/TownOfHost] Replenish the missing quotations (PR#1002)




   
既然你们这么说，好好好，我的错，我道歉：我对我正常流程更新翻译道歉，我对我私自添加我的贡献道歉。你们随意吧，反正我摆烂了，我不管csv文件的翻译了。 梦初（MC_AS_Huier） @.***
 …
 ---Original--- From: @.&gt; Date: Thu, Aug 11, 2022 18:32 PM To: _@**._&gt;; Cc: ***@***.***@._&gt;; Subject: Re: [tukasa0001/TownOfHost] Replenish the missing quotations (PR #1002) Don't change the subject with monopoly. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: _@_.*&gt;
  
你挑衅谁呢？年龄不大倒挺嚣张啊，不会说话的话建议把九年义务教育语文学完，你估计一年都没学完吧 你和那个硬币捆一块没一个拿得出手的作品，toh还要跟我们抢，以后不知道你要走向什么道路，老子不敢想，想了也是浪费时间 既然你会看github写csharps就应该走些正当的道路，受正规教育将来有大用，比你在这盗走别人的劳动成果不知道强几万倍
  
乐了，我们硬币什么时候和两个少年他们合作了？我们硬币汉化我们自己的，根本就没参与你们这讨论里面，关我们硬币什么事？惹你们了？存心找我们茬？

**Pull request closed without merging**
