### PR TITLE
TChinese csv update

### PR DESCRIPTION
**Pull request by NetherDragonTw**

### CODE REVIEW

**Comment by soukunsandesu** [comment]
This branch is very old.
Please update a branch.

**Comment by NetherDragonTw** [comment]
> This branch is very old. Please update this branch.

ummmm, this branch is newest develop branch, wdym?

**Comment by soukunsandesu** [comment]
please do ``git fetch upstream`` and ``git pull`` on terminal.

**Comment by NetherDragonTw** [comment]
> git fetch upstream

fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.
command ouput

**Comment by soukunsandesu** [comment]
sorry. Please try do ``git fetch``

**Comment by NetherDragonTw** [comment]
> git fetch

and do git pull?

**Comment by soukunsandesu** [comment]
yes

**Comment by NetherDragonTw** [comment]
> yes

Already up to date.
command output

**Comment by NetherDragonTw** [comment]
ok, i updated the branch

**Comment by soukunsandesu** [comment]
Please re-create the branch and ask again.

**Pull request closed without merging**
