### PR TITLE
[main]Repository Cleanup

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
Please check the previews:
- **[README]** ( **EN** )
- **[Roles]** ( **EN** )
- **[Settings]** ( **EN** )

### Changes

- Moved source code into `/Source/`
- Moved thumbnail into `/Resources/`
- Moved English README into `/Documentation/EN/`
- Moved roles & settings into dedicated files
- Added badges for twitter, discord & license
- Added links to English & Japanese versions
- Added quicklinks bar
- General formatting / spacing

### Repository Recommendations

- Disable unused widget `Packages`
- Disable unused tabs:
  - `Actions`
  - `Projects`

[README]: https://github.com/ElectronicsArchiver/TownOfHost/blob/main/Documentation/EN/README.md
[Roles]: https://github.com/ElectronicsArchiver/TownOfHost/blob/main/Documentation/EN/Roles.md
[Settings]: https://github.com/ElectronicsArchiver/TownOfHost/blob/main/Documentation/EN/Settings.md

### CODE REVIEW

**Comment by yurinakira** [comment]
メモ
マージ先がmainになっている。
v1.4v1.5でクリーンアップしてるので、作業が一番重複している。

**Comment by ElectronicsArchiver** [comment]
oh . .

**Comment by ElectronicsArchiver** [comment]
So do you still want the commit?

If so,

> We will be moving the folder tree, so please limit your request to changing the contents of the file.

just the README with the documentation or just the README?

**Comment by tanakanira0118** [comment]
Please just the README.
Detailed descriptions of roles, settings, etc. will be written in the Wiki.

**Comment by ElectronicsArchiver** [comment]
Is it fine like this?

*I left the links to `Settings` & `Roles` as `#` for when you have them.`
*I left the `Resources` folder as is.*

**Review by tanakanira0118 — APPROVED** [review]

**Pull request closed without merging**
